### ISSUE TITLE
Backend - Server-Management-Funktionen 

### ISSUE THREAD

**Issue by max5800** [max5800/beammp-server-mgmt#3]
### Tasks
- [ ] add command: start
- [ ] add command: stop
- [ ] add command: restart / reload

**Comment by max5800** [comment]
### Server Actions to implement
- [ ] add command: start
- [ ] add command: stop
- [ ] add command: restart / reload

**Comment by max5800** [comment]
Server Command Routes work, need to compile beammp to further test.

**Comment by max5800** [comment]
config-editor route implemented, but not tested. 
Next Step, editor route testing.

**Comment by max5800** [comment]
test hat funktioniert, aber ich habe festgestellt, dass eine authentifizierung für das benutzen der api implementiert werden muss.
Dafür werde ich jetzt jwt (json web token) verwenden. 
Die Implementierung ist der nächste schritt.
